FROM lajunta/ruby

# Set local timezone
ENV MIRROR "https://mirrors.tuna.tsinghua.edu.cn/alpine/latest-stable/main/"
RUN echo $MIRROR > /etc/apk/repositories && \
    apk add --update tzdata && \
    cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
    echo "Asia/Shanghai" > /etc/timezone

# Install your app's runtime dependencies in the container
RUN apk add --update --virtual runtime-deps nodejs libffi-dev readline

# Bundle into the temp directory
WORKDIR /tmp
ADD Gemfile* ./

RUN apk add --virtual build-deps build-base libressl2.7-libssl libc-dev linux-headers libxml2-dev libxslt-dev readline-dev && \
    bundle install --without development test --clean --jobs=2 && \
    apk del build-deps

# Copy the app's code into the container
ENV APP_HOME /app
COPY . $APP_HOME
WORKDIR $APP_HOME

# Configure production environment variables
ENV RAILS_ENV=production \
    RACK_ENV=production

# Expose port 3000 from the container
EXPOSE 3000

# Run puma server by default
CMD ["bundle", "exec", "puma"]
