# need also gem install 
# gem install grpc-tools
# then make proto file to lib directory
# grpc_tools_ruby_protoc -Iproto --ruby_out=lib --grpc_out=lib proto/ecole.proto
# grpc_tools_ruby_protoc -I /usr/local/include -I. -I $GOPATH/src -I $GOPATH/src/github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis  -I proto --ruby_out=lib --grpc_out=lib proto/ecole.proto

source "http://gems.ruby-china.com/"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gem 'rails'
gem 'grpc'
gem 'puma'
gem 'sass-rails'
gem 'turbolinks'
gem 'jbuilder'
gem 'webpacker'
gem "slim-rails"
gem 'dalli'
gem 'rucaptcha'
gem 'bootsnap'
gem 'mongoid'
gem 'font-awesome-sass'
gem 'kaminari'
gem 'kaminari-mongoid'
gem 'zbox'
gem 'mongo_grid'
gem 'lwqzx_auth'

group :development do
  gem 'web-console'
  gem 'listen'
  gem 'spring'
  gem 'spring-watcher-listen'
end
